version: 0.2

env:
  parameter-store:
    BUCKET: /codebuild/bucketName

phases:
  install:
    commands:
        - git clone https://github.com/kukielp/cra-4-zain
        - npm install
  build:
    commands:
        - npm run build
        - aws s3 sync build/ s3://$BUCKET
